-- Script SQL para crear tablas del módulo de facturación
-- Ejecutar este script en MySQL si no puedes usar php artisan migrate

USE laravel;

-- Tabla: cai_autorizaciones
CREATE TABLE IF NOT EXISTS `cai_autorizaciones` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `rtn_emisor` varchar(18) NOT NULL COMMENT 'Formato: 0000-0000-000000 (14 dígitos + 2 guiones)',
  `nombre_comercial` varchar(255) NOT NULL,
  `punto_emision` varchar(3) NOT NULL COMMENT 'Ej: "001"',
  `tipo_documento` enum('FACTURA','NOTA_CREDITO','NOTA_DEBITO') NOT NULL,
  `cai` varchar(50) NOT NULL COMMENT 'Número CAI completo',
  `prefijo` varchar(10) NOT NULL COMMENT 'Ej: "FAC-001-001"',
  `rango_inicial` bigint unsigned NOT NULL,
  `rango_final` bigint unsigned NOT NULL,
  `ultimo_correlativo_usado` bigint unsigned NOT NULL DEFAULT '0',
  `fecha_limite_emision` date NOT NULL COMMENT 'Fecha de vencimiento del CAI',
  `estado` enum('ACTIVO','AGOTADO','VENCIDO','INACTIVO') NOT NULL DEFAULT 'ACTIVO',
  `constancia_registro` varchar(50) DEFAULT NULL COMMENT 'Número de constancia del establecimiento',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cai_autorizaciones_estado_fecha_limite_emision_index` (`estado`,`fecha_limite_emision`),
  UNIQUE KEY `unique_correlativo` (`rtn_emisor`,`punto_emision`,`tipo_documento`,`ultimo_correlativo_usado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: facturas
CREATE TABLE IF NOT EXISTS `facturas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `cai_autorizacion_id` bigint unsigned NOT NULL,
  `numero_factura` varchar(50) NOT NULL COMMENT 'Prefijo + Correlativo completo',
  `numero_correlativo` bigint unsigned NOT NULL COMMENT 'Solo el número',
  `cai` varchar(50) NOT NULL COMMENT 'Denormalizado para reportes',
  `cliente_id` bigint unsigned DEFAULT NULL,
  `cliente_rtn` varchar(20) NOT NULL COMMENT 'OBLIGATORIO: DNI, RTN o Pasaporte del cliente',
  `cliente_nombre` varchar(255) NOT NULL COMMENT 'OBLIGATORIO',
  `cliente_direccion` text,
  `cliente_telefono` varchar(20) DEFAULT NULL,
  `cliente_email` varchar(100) DEFAULT NULL,
  `mantenimiento_id` bigint unsigned DEFAULT NULL,
  `orden_trabajo_id` bigint unsigned DEFAULT NULL,
  `fecha_emision` datetime NOT NULL COMMENT 'OBLIGATORIO',
  `fecha_limite_emision` date NOT NULL COMMENT 'Del CAI, denormalizado',
  `tipo_pago` enum('CONTADO','CREDITO','TARJETA','TRANSFERENCIA') NOT NULL,
  `dias_credito` int DEFAULT NULL COMMENT 'Si tipo_pago = CREDITO',
  `subtotal_gravado_15` decimal(12,2) NOT NULL DEFAULT '0.00',
  `subtotal_gravado_18` decimal(12,2) NOT NULL DEFAULT '0.00',
  `subtotal_exento` decimal(12,2) NOT NULL DEFAULT '0.00',
  `subtotal` decimal(12,2) NOT NULL COMMENT 'Suma de todos los subtotales',
  `isv_15` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '15% sobre gravado_15',
  `isv_18` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '18% sobre gravado_18',
  `isv_total` decimal(12,2) NOT NULL COMMENT 'Suma de ISV',
  `total_a_pagar` decimal(12,2) NOT NULL COMMENT 'subtotal + isv_total',
  `exenta` tinyint(1) NOT NULL DEFAULT '0',
  `orden_compra_exenta` varchar(50) DEFAULT NULL COMMENT 'OBLIGATORIO si exenta=true',
  `constancia_exoneracion` varchar(50) DEFAULT NULL,
  `estado` enum('VIGENTE','ANULADA','CANCELADA') NOT NULL DEFAULT 'VIGENTE',
  `motivo_anulacion` text,
  `anulada_por` bigint unsigned DEFAULT NULL,
  `anulada_at` datetime DEFAULT NULL,
  `emitida_por` bigint unsigned NOT NULL COMMENT 'Usuario que emitió',
  `impresa` tinyint(1) NOT NULL DEFAULT '0',
  `impresa_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `facturas_cai_autorizacion_id_numero_correlativo_unique` (`cai_autorizacion_id`,`numero_correlativo`),
  KEY `facturas_cai_autorizacion_id_foreign` (`cai_autorizacion_id`),
  KEY `facturas_cliente_id_foreign` (`cliente_id`),
  KEY `facturas_mantenimiento_id_foreign` (`mantenimiento_id`),
  KEY `facturas_anulada_por_foreign` (`anulada_por`),
  KEY `facturas_emitida_por_foreign` (`emitida_por`),
  KEY `facturas_fecha_emision_index` (`fecha_emision`),
  KEY `facturas_cliente_rtn_index` (`cliente_rtn`),
  KEY `facturas_estado_index` (`estado`),
  KEY `facturas_created_at_index` (`created_at`),
  CONSTRAINT `facturas_cai_autorizacion_id_foreign` FOREIGN KEY (`cai_autorizacion_id`) REFERENCES `cai_autorizaciones` (`id`),
  CONSTRAINT `facturas_cliente_id_foreign` FOREIGN KEY (`cliente_id`) REFERENCES `users` (`id`),
  CONSTRAINT `facturas_mantenimiento_id_foreign` FOREIGN KEY (`mantenimiento_id`) REFERENCES `maintenances` (`id`),
  CONSTRAINT `facturas_anulada_por_foreign` FOREIGN KEY (`anulada_por`) REFERENCES `users` (`id`),
  CONSTRAINT `facturas_emitida_por_foreign` FOREIGN KEY (`emitida_por`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: detalle_facturas
CREATE TABLE IF NOT EXISTS `detalle_facturas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `factura_id` bigint unsigned NOT NULL,
  `numero_linea` int NOT NULL COMMENT 'Orden de la línea',
  `producto_servicio_id` bigint unsigned DEFAULT NULL,
  `codigo_producto` varchar(50) DEFAULT NULL,
  `descripcion` text NOT NULL COMMENT 'OBLIGATORIO',
  `cantidad` decimal(10,2) NOT NULL COMMENT 'OBLIGATORIO',
  `unidad_medida` varchar(20) NOT NULL DEFAULT 'UND' COMMENT 'Ej: "UND", "HRS", "KG"',
  `precio_unitario` decimal(12,2) NOT NULL COMMENT 'OBLIGATORIO',
  `tipo_gravamen` enum('GRAVADO_15','GRAVADO_18','EXENTO') NOT NULL,
  `tasa_isv` decimal(5,2) NOT NULL COMMENT '15.00 o 18.00 o 0.00',
  `descuento_porcentaje` decimal(5,2) NOT NULL DEFAULT '0.00',
  `descuento_monto` decimal(12,2) NOT NULL DEFAULT '0.00',
  `subtotal_linea` decimal(12,2) NOT NULL COMMENT '(cantidad * precio_unitario) - descuento',
  `isv_linea` decimal(12,2) NOT NULL COMMENT 'subtotal_linea * (tasa_isv/100)',
  `total_linea` decimal(12,2) NOT NULL COMMENT 'subtotal_linea + isv_linea',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `detalle_facturas_factura_id_foreign` (`factura_id`),
  KEY `detalle_facturas_factura_id_numero_linea_index` (`factura_id`,`numero_linea`),
  CONSTRAINT `detalle_facturas_factura_id_foreign` FOREIGN KEY (`factura_id`) REFERENCES `facturas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla: logs_facturacion
CREATE TABLE IF NOT EXISTS `logs_facturacion` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `factura_id` bigint unsigned NOT NULL,
  `usuario_id` bigint unsigned NOT NULL,
  `accion` enum('CREACION','ANULACION','IMPRESION','MODIFICACION') NOT NULL,
  `descripcion` text NOT NULL,
  `datos_anteriores` json DEFAULT NULL,
  `datos_nuevos` json DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `logs_facturacion_factura_id_foreign` (`factura_id`),
  KEY `logs_facturacion_usuario_id_foreign` (`usuario_id`),
  CONSTRAINT `logs_facturacion_factura_id_foreign` FOREIGN KEY (`factura_id`) REFERENCES `facturas` (`id`),
  CONSTRAINT `logs_facturacion_usuario_id_foreign` FOREIGN KEY (`usuario_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
